sylius_shop_account_order_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexAction
        _sylius:
            template: VcareWebBundle:Account/Order:index.html.twig
            grid: sylius_shop_account_order
            section: shop_account

sylius_shop_account_order_show:
    path: /{number}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            template: VcareWebBundle:Account/Order:show.html.twig
            grid: sylius_shop_account_order
            section: shop_account
            repository:
                method: findOneByNumberAndCustomer
                arguments:
                    - $number
                    - 'expr:service("sylius.context.customer").getCustomer()'

sylius_shop_account_order_incoice:
    path: /invoice/{number}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            template: VcareWebBundle:Account/Order:invoice.html.twig
            grid: sylius_shop_account_order
            section: shop_account
            repository:
                method: findOneByNumberAndCustomer
                arguments:
                    - $number
                    - 'expr:service("sylius.context.customer").getCustomer()'
