imports:
    - { resource: "sylius_addressing.yml" }
    - { resource: "sylius_channel.yml" }
    - { resource: "sylius_mailer.yml" }
    - { resource: "sylius_order.yml" }
    - { resource: "sylius_customer.yml" }
