sylius_order:
    resources:
        order:
            classes:
                controller: Vcare\Bundle\WebBundle\Controller\OrderController
    expiration:
        cart: '1 hour'
        order: '1 days'
