sylius_admin_partial_taxon_tree:
    path: /product-tree
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            template: $template
            repository:
                method: findChildren
                arguments:
                    - "expr:service('vcare.context.channel_settings').getProductTaxonRootCode()"
                    - "expr:service('sylius.context.locale').getLocaleCode()"

sylius_admin_partial_taxon_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:showAction
        _sylius:
            template: $template
            vars: $vars
