sylius_admin_partial_product_taxon_tree:
    path: /product-tree
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            template: $template
            repository:
                method: findChildren
                arguments:
                    - "expr:service('vcare.context.channel_settings').getProductTaxonRootCode()"

sylius_admin_partial_taxon_tree:
    path: /tree
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            template: $template
            repository:
                method: findRootNodes
