# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "config.yml" }

monolog:
    handlers:
        type: service
        id: snc_redis.monolog.handler
        level: error

snc_redis:
    clients:
        monolog:
            type: phpredis
            alias: monolog
            dsn: '%redis_monolog_dns%'
            logging: false
            options:
                connection_persistent: true
    monolog:
        client: monolog
        key: monolog
