sylius_shop:
    resource: "sylius/shop/app/routing.yml"

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_admin:
    resource: "sylius/admin/app/routing.yml"
    prefix: /admin

sylius_admin_api:
    resource: "@SyliusAdminApiBundle/Resources/config/routing.yml"
    prefix: /api

toro_media:
    resource: "@ToroMediaBundle/Resources/config/routing.yml"

#sylius_shop_default_locale:
#    path: /
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.shop.locale_switch:switchAction

vcare_posts:
    resource: "vcare/routing/post.yml"

# must to be end of file.
toro_cms:
    resource: "@ToroCmsBundle/Resources/config/routing.yml"
