# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_paysbuy:
    resource: "@DosPaysbuyBundle/Resources/config/routing.xml"
    prefix:   /_paysbuy

_main:
    resource: routing.yml
