# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

vcare_web:
    resource: "@VcareWebBundle/Resources/config/routing.yml"

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"

sylius_admin:
    resource: "sylius/admin/app/routing.yml"
    prefix: /admin

sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api

toro_media:
    resource: "@ToroMediaBundle/Resources/config/routing.yml"

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
