# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin_dashboard_redirect:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_admin_dashboard
        permanent: true

toro_media:
    resource: "@ToroMediaBundle/Resources/config/routing.yml"

sylius_shop:
    resource: "sylius/shop/app/routing.yml"

sylius_admin:
    resource: "sylius/admin/app/routing.yml"
    prefix: /admin

#sylius_api:
#    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
#    prefix: /api

# must to be end of file.
toro_cms:
    resource: "@ToroCmsBundle/Resources/config/routing.yml"
