imports:
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }

liip_imagine:
    filter_sets:
        sylius_admin_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        sylius_admin_product_thumbnail:
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
