toro_admin_cms_page:
    resource: |
        alias: toro.page
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: index
        grid: toro_admin_page
        vars:
          all:
            templates:
                form: ToroCmsBundle:Admin/Page:_semantic_form.html.twig
          index:
            icon: ti-book
    type: sylius.resource
