sylius_grid:
    grids:
        sylius_admin_order:
            fields:
                channel:
                    enabled: false

        toro_admin_page:
            driver:
                name: doctrine/orm
                options:
                    class: Vcare\Bundle\WebBundle\Model\Page
            sorting:
                createdAt: desc
            filters:
                title:
                    type: string
                    label: Title
            fields:
                published:
                    type: twig
                    label: Published
                    options:
                        template: SyliusAdminBundle:Grid/Field:yesNo.html.twig
                partial:
                    type: twig
                    label: Partial
                    options:
                        template: SyliusAdminBundle:Grid/Field:yesNo.html.twig
                title:
                    type: string
                    label: Title
                slug:
                    type: string
                    label: Slug
                createdAt:
                    type: datetime
                    label: Create at
                    sortable: ~
                    options:
                        format: d-m-Y H:i
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
