vcare_shop_post_index:
    path: /posts
    defaults:
        _controller: toro.controller.post:indexAction
        _sylius:
            template: VcareWebBundle:Post:index.html.twig
            permission: false
            paginate: 5
            repository:
                method: createPaginator
                arguments: [{ published: true, featured: true, channel: 'expr:service("sylius.context.channel").getChannel()' }]

vcare_shop_post_show:
    path: /posts/{slug}
    methods: [GET]
    defaults:
        _controller: toro.controller.post:showAction
        _sylius:
            template: VcareWebBundle:Post:show.html.twig
            repository:
                method: findOneBySlugAndChannel
                arguments:
                    - $slug
                    - 'expr:service("sylius.context.channel").getChannel()'
