parameters:
    locked_theme: "intbizth/vcare"
    hwi_oauth.authentication.provider.oauth.class: Vcare\Bundle\WebBundle\OAuth\OAuthProvider

imports:
    - { resource: "sylius_product.yml" }
    - { resource: "sylius_grid.yml" }
    - { resource: "toro_cms.yml" }
    - { resource: "toro_tagging.yml" }
    - { resource: "fm_elfinder.yml" }
    - { resource: "liip_imagine.yml" }
    - { resource: "stof_doctrine_extensions.yml" }
    - { resource: "sylius_resource.yml" }
    - { resource: "stfalcon_tinymce.yml" }
