sylius_grid:
    grids:
        sylius_admin_taxon:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.taxon.class%"
                    repository:
                        method: createListQueryBuilderLocaled
                        arguments: [ "%locale%", "expr:service('vcare.context.channel_settings').getProductTaxonRootContext()" ]
            filters:
                name:
                    type: string
                    options:
                        fields: [translation.name]
