l00:
    host: 139.162.61.107
    port: 25252
    user: root
    #password: zohxoh9Nin9xaiphi4ziech8
    forward_agent: ~
    identity_file: ~
    stage: production
    deploy_path: "/var/www"
    branch: vcare
    config:
        base_parameters: ./app/config/parameters.yml
        redis_password: aiwe4Eewae8ciek3ro6Waire
        supervisor_password: aengayah5aim3ohru3uawaiT
    parameters:
        mailer_transport: gmail
        mailer_host: ~
        mailer_user: "vcareasia.thailand@gmail.com"
        mailer_password: aeth3ieb4yooBeesahhiThae
        database_host: localhost
        database_port: 7890
        database_name: vcare_shop
        database_user: root
        database_password: we2atheiz2pe9ohxo6kie4Ai
        redis_monolog_dns: 'redis://dummy:ohnaicahn4ug9gaquaSh3Tha@localhost:1234/0'
        redis_session_dns: 'redis://dummy:ohnaicahn4ug9gaquaSh3Tha@localhost:1234/1'
        redis_swiftmailer_dns: 'redis://dummy:ohnaicahn4ug9gaquaSh3Tha@localhost:1234/2'
        paysbuy_sandbox: true
