sylius_shop_order_pay:
    path: /{paymentId}/pay
    methods: [GET]
    defaults:
        _controller: sylius.controller.payum:prepareCaptureAction
        _sylius:
            redirect:
                route: sylius_shop_order_after_pay

sylius_shop_order_after_pay:
    path: /after-pay
    methods: [GET]
    defaults:
        _controller: sylius.controller.payum:afterCaptureAction

sylius_shop_order_thank_you:
    path: /thank-you
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:thankYouAction
        _sylius:
            template: VcareWebBundle:Checkout:thankYou.html.twig

sylius_shop_order_show:
    path: /{tokenValue}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            template: VcareWebBundle:Checkout:orderDetails.html.twig
            repository:
                method: findOneBy
                arguments: [tokenValue: $tokenValue]
