sylius_shop_product_show:
    path: /products/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:showAction
        _sylius:
            template: VcareWebBundle:Product:show.html.twig
            repository:
                method: findOneBySlugAndChannel
                arguments:
                    - $slug
                    - 'expr:service("sylius.context.channel").getChannel()'
