sylius_shop_province_choice:
    path: /province-choice
    defaults:
        _controller: sylius.controller.province:choiceOrTextFieldFormAction
        _sylius:
            template: VcareWebBundle:Checkout:_provinces.html.twig
