sylius_shop_product_show:
    path: /products/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:showAction
        _sylius:
            template: "@VcareWeb/Product/show.html.twig"
            repository:
                method: findOneByChannelAndSlug
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - $slug

sylius_shop_product_index:
    path: /category/{slug}
    methods: [GET]
    defaults:
        locale: "%locale%"
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: '@VcareWeb/Product/taxons.html.twig'
            grid: sylius_shop_product
            vars:
                taxon: "expr:service('sylius.repository.taxon').findOneBySlug($slug, $locale)"
    requirements:
        slug: .+
