route_shop_homepage:
    path: /
    defaults:
        _controller: sylius.controller.shop.homepage:indexAction

sylius_shop_homepage:
    path: /
    defaults:
        _controller: sylius.controller.shop.homepage:indexAction

sylius_shop_security:
    resource: "routing/security.yml"

sylius_shop_product:
    resource: "routing/product.yml"

sylius_shop_cart:
    resource: "routing/cart.yml"
    prefix: /cart

sylius_shop_checkout:
    resource: "routing/checkout.yml"
    prefix: /checkout

sylius_shop_order:
    resource: "routing/order.yml"
    prefix: /order

sylius_shop_account:
    resource: "routing/account.yml"
    prefix: /account

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

hwi_oauth:
    resource: "routing/hwi_oauth.yml"

sylius_shop_switch_currency:
    path: /switch-currency/{code}
    defaults:
        _controller: sylius.controller.shop.currency_switch:switchAction

sylius_shop_switch_locale:
    path: /switch-locale/{code}
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

sylius_shop_partial:
    resource: "@SyliusShopBundle/Resources/config/routing/partial.yml"
    prefix: /_partial

vcare_shop_partial:
    resource: "@VcareWebBundle/Resources/config/routing_partial.yml"
    prefix: /_partial

sylius_shop_user:
    resource: "@SyliusShopBundle/Resources/config/routing/shop_user.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
