# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_homepage:
    path: /
    defaults:
        _controller: sylius.controller.shop.homepage:indexAction

sylius_shop_security:
    resource: "routing/security.yml"

sylius_shop_taxon:
    resource: "routing/taxon.yml"

sylius_shop_product:
    resource: "routing/product.yml"

sylius_shop_payment:
    resource: "routing/payment.yml"

sylius_shop_provinces:
    resource: "routing/provinces.yml"

sylius_shop_cart:
    resource: "routing/cart.yml"
    prefix: /cart

sylius_shop_checkout:
    resource: "routing/checkout.yml"
    prefix: /checkout

sylius_shop_order:
    resource: "routing/order.yml"
    prefix: /order

sylius_shop_account:
    resource: "routing/account.yml"
    prefix: /account

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_shop_switch_currency:
    path: /switch-currency/{code}
    defaults:
        _controller: sylius.controller.shop.currency_switch:switchAction

sylius_shop_switch_locale:
    path: /switch-locale/{code}
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

sylius_shop_partial:
    resource: "@SyliusShopBundle/Resources/config/routing/partial.yml"
    prefix: /_partial

sylius_shop_verification:
    prefix: /verify
    resource: "@SyliusShopBundle/Resources/config/routing/verification.yml"

sylius_sitemap:
    path: /sitemap.{_format}
    methods: [GET]
    defaults:
        _controller: sylius.controller.sitemap:showAction
        _format: xml
    requirements:
        _format: xml

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
