sylius_resource:
    resources:
        vcare.news_subscriber:
            classes:
                model: Vcare\Bundle\WebBundle\Model\NewsSubscriber
                interface: Vcare\Bundle\WebBundle\Model\NewsSubscriberInterface
                controller: Vcare\Bundle\WebBundle\Controller\NewsSubscriberController
                form: Vcare\Bundle\WebBundle\Form\Type\NewsSubscriberType
