toro_widget:
    widgets:
        Toro\Bundle\WidgetBundle\Twig\DemoWidget:
            options:
                template: ToroWidgetBundle:widgets:demo.html.twig
        Toro\Bundle\WidgetBundle\Twig\Demo2Widget:
            options:
                template: ToroWidgetBundle:widgets:demo2.html.twig
        Toro\Bundle\WidgetBundle\Twig\DemoLazyWidget:
            options:
                template: ToroWidgetBundle:widgets:lazy.html.twig
        Toro\Bundle\WidgetBundle\Twig\DemoAutoRefreshWidget:
            options:
                template: ToroWidgetBundle:widgets:auto_refresh.html.twig
        Toro\Bundle\WidgetBundle\Twig\DemoAutoRefreshOnScreenWidget:
            options:
                template: ToroWidgetBundle:widgets:auto_refresh_onscreen.html.twig
        Toro\Bundle\WidgetBundle\Twig\DemoLazyAndAutoRefreshWidget:
            options:
                template: ToroWidgetBundle:widgets:auto_refresh_lazy.html.twig

        # news
        Toro\Bundle\NewsBundle\Widget\LatestNewsWidget:
            options:
                template: ToroCmsBundle:widgets/news:latest_news.html.twig
        Toro\Bundle\NewsBundle\Widget\HotNewsWidget:
            options:
                template: ToroCmsBundle:widgets/news:hot_news.html.twig
        Toro\Bundle\NewsBundle\Widget\FeaturedNewsWidget:
            options:
                template: ToroCmsBundle:widgets/news:featured_news.html.twig
        Toro\Bundle\NewsBundle\Widget\SimilarNewsWidget:
            options:
                template: ToroCmsBundle:widgets/news:similar_news.html.twig
        Toro\Bundle\NewsBundle\Widget\AnnouncementWidget:
            options:
                template: ToroCmsBundle:widgets/announcement:index.html.twig

        # soccer
        Toro\Bundle\SoccerBundle\Widget\RecentMatchesWidget:
            options:
                template: ToroWidgetBundle:widgets:recent_matches.html.twig
        Toro\Bundle\SoccerBundle\Widget\StandingWidget:
            options:
                template: ToroCmsBundle:widgets/standings:top_standing.html.twig
        Toro\Bundle\SoccerBundle\Widget\SeasonClubMembersWidget:
            options:
                template: ToroCmsBundle:widgets/clubs:season_club_members.html.twig
        Toro\Bundle\SoccerBundle\Widget\PersonalTopScorerWidget:
            options:
                template: ToroCmsBundle:widgets/personals:top_scorer.html.twig
