toro_admin_cms_page:
    resource: |
        alias: toro.page
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: toro_admin_page
        vars:
          create:
            templates:
                form: ToroCmsBundle:Admin/Page:_form_semantic_create.html.twig
          update:
            templates:
                form: ToroCmsBundle:Admin/Page:_form_semantic.html.twig
          index:
            icon: ti-book
    type: sylius.resource
